### ISSUE TITLE
Code snippets are not working

### ISSUE THREAD

**Issue by JashanBansal0708** [theranbrig/ejs-snippets#1] opened 2019-01-07 10:58 UTC
All the code snippets that are defined in the documentation are not working. (Not even a single working)

**Comment by theranbrig** [comment] 2019-02-26 15:32
I just checked and it was working in my editor.  Did you reload in VS Code?  Though you have no need to reload in the latest VS Code version.

**Comment by theranbrig** [comment] 2019-03-10 03:20
I have closed this issue since there was no further comment.  If they are still not working please let me know and I will check things out.

**Closed** 2019-03-10 03:20 UTC

**Comment by KendraArb** [comment] 2019-06-08 03:06
I am running into this issue as well.  I disabled all my other extensions to see if it was a problem with any of those, and I also reloaded in VS Code, but neither have been able to get the snippets working.

**Comment by theranbrig** [comment] 2019-06-08 06:51
I must admit I haven't worked with EJS in a bit, however when I tested it today it worked perfectly in a test EJS file. Not sure what the issue is?  Please let me know if you can give any more detail on what your issue is.

<img width="770" alt="Screen Shot 2019-06-08 at 3 46 06 PM" src="https://user-images.githubusercontent.com/29407645/59143321-f36cb200-8a04-11e9-865d-7149a67de76c.png">
<img width="415" alt="Screen Shot 2019-06-08 at 3 46 18 PM" src="https://user-images.githubusercontent.com/29407645/59143327-fc5d8380-8a04-11e9-8bf9-e5ac37fae2a0.png">

**Comment by JashanBansal0708** [comment] 2019-06-08 07:20
@theranbrig I installed the extension again and check if its now working, but no it is not  working still. I don't know the issue, but it is really not working as i have checked it two times now.

![image](https://user-images.githubusercontent.com/36573762/59143753-ba741380-89eb-11e9-9024-120d22f2655e.png)

**Comment by theranbrig** [comment] 2019-06-08 08:46
I just uninstalled and reinstalled.  It worked on mine.  Sometimes I have noticed that snippets take a second to load when I open a new editor.  I looked through my settings and the only thing I have with EJS is: 

```json
"files.associations": {
    "*.ejs": "ejs"
  },
```

This was from back in the day so I am not sure if this helps?

**Comment by KendraArb** [comment] 2019-06-10 14:13
I went in and added these to the settings, but it didn't seem to help.
![image](https://user-images.githubusercontent.com/39602038/59201314-6423e380-8b57-11e9-8540-c534ad7da9f8.png)

![image](https://user-images.githubusercontent.com/39602038/59201386-92092800-8b57-11e9-810d-c437bb466d3e.png)
 Thanks for trying.  I think I'm going to switch over to handlebars in favor of an easier syntax.
